"""Generate preliminary mirrors from semantic terms actually used in author files."""
from pathlib import Path
import re
root = Path(__file__).resolve().parents[1]
def uncomment(text):
    return re.sub(r"(?<!\\)%[^\n]*", "", text)
definitions = uncomment((root / 'glossary/terms.tex').read_text())
known = set(re.findall(r"\\(?:newglossaryentry|newacronym)(?:\[[^\]]*\])?\{([^}]+)\}", definitions))
visited = set()
def walk(file):
    file = file.resolve()
    if file in visited or not file.is_relative_to(root) or not file.exists(): return ''
    visited.add(file)
    text = uncomment(file.read_text())
    for name in re.findall(r"\\(?:input|include)\{([^}]+)\}", text):
        child = root / (name if name.endswith('.tex') else name + '.tex')
        if child.parts[-2] != 'glossary': text += '\n' + walk(child)
    return text
body = walk(root / 'main.tex')
# Front matter is loaded by class commands rather than main.tex inputs.
for file in sorted((root / 'front-matter').glob('*.tex')): body += '\n' + walk(file)
used = set(re.findall(r"\\(?:gls|Gls|glspl|Glspl|glsfirst|glstext)\*?\{([^}]+)\}", body))
entries = set()
for key in used:
    if key.startswith('acr-'): entries.add(key)
    for candidate in ('en-' + key, 'acr-' + key):
        if candidate in known: entries.add(candidate)
output = '% Generated by tools/prepare_terms.py; edit glossary/terms.tex instead.\n'
output += ''.join('\\glsadd{' + key + '}\n' for key in sorted(entries))
target = root / 'glossary/preliminary-acronyms.tex'
if not target.exists() or target.read_text() != output: target.write_text(output)
